### ISSUE TITLE
no pcb doc

### ISSUE THREAD

**Issue by OwenBrotherwood** [bbcmicrobit/hardware#1]
The hardware documentation only shows the diagram of circuits, BOM but does not document unknown possibilities in the test points of the PCB

**Comment by nealmcb** [comment]
See the PDF file included as part of #2, as identified and clarified at

* [Test point map for BBC micro:bit \- Electrical Engineering Stack Exchange](https://electronics.stackexchange.com/questions/373780/test-point-map-for-bbc-microbit)

And of course, merging #2 would fix this bug ;)

**Comment by jaustin** [comment]
I've now merged the test point map, and there's a layout for the reference design at https://github.com/microbit-foundation/microbit-reference-design/ so I'm closing this
