### ISSUE TITLE
Schematics for new version 1.5    when?

### ISSUE THREAD

**Issue by zfm076** [bbcmicrobit/hardware#4]

**Comment by tkreyche** [comment]
Yes, please post the new schematics - pretty basic request.

Just looked on the other issues - same request - why nothing posted yet after a year? Glacial progress is more like it.

"It might be a slow process, but this is high in our priority list, so as soon as we can publish the schematics we'll update this repository."

**Comment by rei-vilo** [comment]
See #3.
